name: Deploy Node.js App to Apache Tomcat
'on':
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Log into Docker Hub
        run: >-
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
          --password-stdin
      - name: Build Node.js App
        run: |
          npm install
          npm run build
      - name: Build Docker Image
        run: docker build -t Dockerfile .
      - name: Push Docker Image to Docker Hub
        run: 'docker push manilmunjal/Dockerfile:latest'
      - name: Run Docker Container
        run: 'docker run -d -p 8080:8080 manilmunjal/Dockerfile:latest'
